CREATE TABLE `myproject`.`ref_data` (
  `ID` INT NOT NULL,
  `TYPE` VARCHAR(45) NOT NULL,
  `VALUE` VARCHAR(45) NOT NULL,
  `DISPLAY_VALUE` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `SORT_ORDER` VARCHAR(45) NULL,
  `ACTIVE_FLAG` INT NULL,
  PRIMARY KEY (`ID`));

  